name: test-action
on:
  release:
    types: [released, prereleased]
inputs:
  ENV_SHORTNAME:
    description: "ENV_SHORTNAME"
    required: true
  WEBHOOK_URL:
    required: true
jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Github Releases To Discord
        if: ${{ inputs.ENV_SHORTNAME == 'staging' || inputs.ENV_SHORTNAME == 'prod' }}
        uses: RifkyHernanda3/publish-release@v1.0 # Uses an action in the root directory
        with:
          webhook_url: ${{ inputs.WEBHOOK_URL }}
          username: "Released"
          avatar_url: "https://64.media.tumblr.com/a430ab8260519fddb01972b5339b40dd/4c5f2cc704cd20da-5a/s1280x1920/f85ece47459b5650f1fdd2e2e0aa3d44c2d06005.png"
          footer_title: "Changelog"
